services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    ports:
      - "8081:8080"
    restart: unless-stopped
    env_file: .env
#    environment:
#      - MAVEN_OPTS=-Xmx1024m -XX:MaxPermSize=256m
#    deploy:
#      resources:
#        limits:
#          memory: 2G
